import { writeFile } from "node:fs/promises";

import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";

import { PLUGIN_MANIFEST_SCHEMA } from "../src/plugins/manifest.schema.ts";

const ajv = new Ajv({
  allErrors: true,
  strict: true,
  code: { esm: true, source: true },
});
const validate = ajv.compile(PLUGIN_MANIFEST_SCHEMA);
const runtimeImports: string[] = [];
const compiledValidator = standaloneCode(ajv, validate).replace(
  /const (func\d+) = require\("(ajv\/dist\/runtime\/[^"]+)"\)\.default;/g,
  (_match, localName: string, moduleName: string) => {
    runtimeImports.push(`import ${localName} from "${moduleName}.js";`);
    return "";
  },
);
const generated = [
  "// This file is generated by scripts/generate-plugin-manifest-validator.ts.",
  "// Do not edit it directly.",
  "// @ts-nocheck",
  ...runtimeImports,
  compiledValidator,
  "",
].join("\n");
const output = new URL(
  "../src/plugins/validatePluginManifest.generated.ts",
  import.meta.url,
);

await writeFile(output, generated, "utf8");
