import type { PluginDefinition } from "../../plugins/registry";

export const MEMORA_PLUGIN = {
  manifest: {
    manifestVersion: 1,
    id: "corelib.memora",
    version: "1.0.0",
    name: "Memora",
    description: "Creates flashcards, schedules reviews, and manages learning data.",
    publisher: "Corelib",
    compatibility: { pluginApi: "^1.0.0" },
    dependencies: [{ pluginId: "corelib.library", version: "^1.0.0", optional: true }],
    permissions: [],
    contributions: {
      surfaces: [
        {
          id: "route.memora",
          title: "Memora",
          aliases: ["flashcards", "decks"],
          breadcrumb: ["Memora"],
          group: "Navigate",
          kind: "page",
          quickOpen: true,
          navigation: { defaultPinned: true, order: 20 },
          icon: "memora",
          bindingId: "route.memora",
        },
        {
          id: "route.trash",
          title: "Trash",
          aliases: ["deleted cards"],
          breadcrumb: ["Trash"],
          group: "Navigate",
          kind: "page",
          quickOpen: true,
          navigation: { defaultPinned: true, order: 40 },
          icon: "trash",
          bindingId: "route.trash",
        },
        {
          id: "route.settings.memora",
          title: "Memora",
          aliases: ["learning", "fsrs", "retention", "new cards"],
          breadcrumb: ["Settings", "Apps"],
          group: "Settings",
          kind: "settings",
          quickOpen: true,
          bindingId: "route.settings.memora",
        },
      ],
      commands: [
        {
          id: "action.review-today",
          title: "Review today",
          aliases: ["study", "due cards"],
          breadcrumb: ["Memora"],
          group: "Memora",
          audiences: ["human", "agent"],
          effect: "write",
          bindingId: "action.review-today",
        },
      ],
      searchProviders: [
        { id: "search.decks", group: "Memora", bindingId: "search.decks" },
        { id: "search.cards", group: "Cards", bindingId: "search.cards" },
        { id: "search.trash", group: "Trash", bindingId: "search.trash" },
      ],
      resources: [],
      events: [],
    },
  },
  declaredBindings: [
    "route.memora",
    "route.trash",
    "route.settings.memora",
    "action.review-today",
    "search.decks",
    "search.cards",
    "search.trash",
  ],
} satisfies PluginDefinition;
